version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "ratemycampus-task2"
        LoadBalancerInfo:
          ContainerName: "app"
          ContainerPort: 8080
