version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-xxxxx-1:xxxxxx:task-definition/xxxx-xx:1"
        LoadBalancerInfo:
          ContainerName: "xxxx"
          ContainerPort: xxx
