version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:580420849247:task-definition/vproject-task:1"
        LoadBalancerInfo:
          ContainerName: "app"
          ContainerPort: 8080
