
version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    IMAGE_NAME: "vproject"
    ECR_DOMAIN: "580420849247.dkr.ecr.us-east-1.amazonaws.com"
    580420849247.dkr.ecr.us-east-1.amazonaws.com/vproject
    ECR_REPO: "580420849247.dkr.ecr.us-east-1.amazonaws.com/vproject"
    DOCKERHUB_USERNAME: "habibqayoom6"
    DOCKERHUB_PASSWORD: "dckr_pat_KGwOT_G6WC5hT5uI-AJxN0PcUng"

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub to avoid rate limits...
      - echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_DOMAIN
      - echo Getting Git commit hash...
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=latest

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $IMAGE_NAME:$IMAGE_TAG .

  post_build:
    commands:
      - echo Tagging Docker image...
      - docker tag $IMAGE_NAME:$IMAGE_TAG $ECR_REPO:$IMAGE_TAG
      - echo Pushing Docker image to ECR...
      - docker push $ECR_REPO:$IMAGE_TAG

artifacts:
  files:
    - '**/*'
