
version: 0.2

env:
  variables:
    AWS_REGION: "us-xxxx-1"
    IMAGE_NAME: "xx"
    ECR_DOMAIN: "xxxxx.dkr.ecr.us-xxx-1.amazonaws.com"
    ECR_REPO: "xxx.dkr.ecr.us-xxxx-1.amazonaws.com/xxxxx"
    DOCKERHUB_USERNAME: "xxxx"
    DOCKERHUB_PASSWORD: "xxxx-xxxx"

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub to avoid rate limits...
      - echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_DOMAIN
      - echo Getting Git commit hash...
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=latest

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $IMAGE_NAME:$IMAGE_TAG .

  post_build:
    commands:
      - echo Tagging Docker image...
      - docker tag $IMAGE_NAME:$IMAGE_TAG $ECR_REPO:$IMAGE_TAG
      - echo Pushing Docker image to ECR...
      - docker push $ECR_REPO:$IMAGE_TAG

artifacts:
  files:
    - appspec.yaml
